getSymbols("^GSPC",from="2004-01-01")
gspcRets=diff(log(Cl(GSPC)))
returns=as.numeric(gspcRets)
plot(gspcRets)
hmm=depmix(returns~1,family=gaussian(),nstates=3, data=data.frame(returns=returns))
hmmfit=fit(hmm,verbose=FALSE)
post_probs=posterior(hmmfit)
layout(1:2)
plot(returns, type='l', main="Regime Detection", xlab = "Days", ylab="Returns")
matplot(post_probs[,-1],type='l', main='Regime Posterior Probabilities', xlab="Days", ylab="Probabilities")
legend(x="topright", c('Regime 1',Regime 1'), fill=1:2,bty='n')